# Jekyll configuration for Twinizer documentation
title: Twinizer
description: Kompleksowe narzędzie do tworzenia i manipulowania cyfrowymi bliźniakami systemów sprzętowych i programowych
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false