# Jekyll configuration for Twinizer documentation
title: Twinizer
description: "Kompleksowe narzędzie do tworzenia i manipulowania cyfrowymi bliźniakami systemów sprzętowych i programowych"
url: https://twinizer.github.io
baseurl: /python/docs
author:
  name: Tom Sapletta
  url: https://github.com/twinizer
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub metadata
repository: twinizer/python
github:
  is_project_page: true
  repository_url: https://github.com/twinizer/python
  owner_url: https://github.com/twinizer
  owner_name: Tom Sapletta

# Build settings
markdown: kramdown
highlighter: rouge
