# Jekyll configuration for Twinizer documentation
title: "Twinizer - Multi-Format Conversion and Analysis Tool"
description: "A comprehensive tool for converting between file formats, analyzing code, hardware schematics, and generating documentation"
url: "https://python.twinizer.com"
baseurl: ""

# SEO settings
author:
  name: Tom Sapletta
  url: https://github.com/tom-sapletta-com
logo: /docs/diagrams/logo.png
lang: en_US
locale: en_US

# Social media
social:
  name: Twinizer
  links:
    - https://github.com/twinizer/python

# GitHub metadata
repository: twinizer/python
github:
  is_project_page: true
  repository_url: https://github.com/twinizer/python
  owner_url: https://github.com/twinizer
  owner_name: Tom Sapletta

# Theme settings
theme: jekyll-theme-cayman
show_downloads: true

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: GitHub
    url: https://github.com/twinizer/python

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs"
    values:
      layout: page
      sidebar: docs