title: "Twinizer - Multi-Format Conversion and Analysis Tool"
description: "A comprehensive tool for converting between file formats, analyzing code, hardware schematics, and generating documentation"
author:
  name: "Tom Sapletta"
  url: https://github.com/tom-sapletta-com
lang: "en"
keywords: "python, package management, pip, conda, poetry, converter, requirements.txt, environment.yml, pyproject.toml"
image: "https://github.com/twinizer/python/raw/main/docs/diagrams/logo.png"

# Keep your existing configuration below this
url: https://twinizer.github.io
baseurl: /python/docs
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub metadata
repository: twinizer/python
github:
  is_project_page: true
  repository_url: https://github.com/twinizer/python
  owner_url: https://github.com/twinizer
  owner_name: Tom Sapletta

# Build settings
markdown: kramdown
highlighter: rouge
